# Generated by Django 4.1.7 on 2023-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_a7aniiik_joined_date_a7aniiik_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a7aniiik',
            options={'ordering': ['price'], 'verbose_name': 'Appl product'},
        ),
        migrations.AddField(
            model_name='a7aniiik',
            name='category',
            field=models.CharField(blank=True, choices=[('phone', 'phonee')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='a7aniiik',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
