# Generated by Django 4.1.7 on 2023-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_user_delete_person_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('imag', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('category', models.CharField(blank=True, choices=[('phone', 'phone')], max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Appl product',
                'ordering': ['price'],
            },
        ),
        migrations.DeleteModel(
            name='A7aniiik',
        ),
    ]
