# Generated by Django 4.1.7 on 2023-02-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_aplle_delete_a7aniiik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplle',
            name='imag',
        ),
        migrations.AddField(
            model_name='aplle',
            name='img',
            field=models.ImageField(default='inag', upload_to='data'),
        ),
        migrations.AlterField(
            model_name='aplle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7),
        ),
    ]
