# Generated by Django 4.1.7 on 2023-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_aplle_imag_aplle_img_alter_aplle_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplle',
            name='img',
            field=models.ImageField(upload_to='data'),
        ),
    ]
