# Generated by Django 4.1.7 on 2023-02-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_aplle_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=2, upload_to='photoo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pord_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
