# Generated by Django 4.1.7 on 2023-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_product_product_f_remove_user_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_f',
            name='photo',
            field=models.ImageField(upload_to='data'),
        ),
    ]
