# Generated by Django 4.1.7 on 2023-02-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_f_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pssword_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name_key', models.CharField(max_length=110)),
                ('Last_name_key', models.CharField(max_length=110)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
