# Generated by Django 4.1.7 on 2023-03-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_customer_order_orderitem_product_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
